site_name: DECAF
site_description: Deep Learning Framework for Environmental Contaminant Analysis in DNA Sequences
site_author: DECAF Team
site_url: https://decaf.readthedocs.io

theme:
  name: readthedocs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aaramis/DECAF
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/decaf/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/decaf_bio

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Introduction: introduction.md
  - Installation: installation.md
  - Usage:
    - Quick Start: usage/quick-start.md
    - Advanced Usage: usage/advanced.md
    - Command Reference: usage/commands.md
  - Configuration:
    - Basic Configuration: configuration/basic.md
    - Advanced Configuration: configuration/advanced.md
  - API:
    - API Reference: api/index.md
    - Models: api/models.md
    - Data Processing: api/data.md
    - Utilities: api/utils.md
  - Development:
    - Contributing: contributing.md
    - Testing: testing.md
    - Development Guide: development.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md
    - FAQ: about/faq.md
    - Contributing Guidelines: about/contributing.md
  - Contribuer:
    - Standards de codage: contributing/coding-standards.md
    - Conventions de nommage: contributing/naming-conventions.md
    - Templates de documentation: contributing/documentation-templates.md
  #   - Planning: development/roadmap.md
  #   - Journal des modifications: development/changelog.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aaramis