name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort mypy
    - name: Lint with black
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check imports with isort
      run: |
        isort --check-only --profile black .
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Type check with mypy
      run: |
        mypy decaf/